// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dkv/v0/replication.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence uint64      `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Msg      *PutRequest `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AppendLogRequest) Reset() {
	*x = AppendLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkv_v0_replication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogRequest) ProtoMessage() {}

func (x *AppendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_v0_replication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogRequest.ProtoReflect.Descriptor instead.
func (*AppendLogRequest) Descriptor() ([]byte, []int) {
	return file_dkv_v0_replication_proto_rawDescGZIP(), []int{0}
}

func (x *AppendLogRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AppendLogRequest) GetMsg() *PutRequest {
	if x != nil {
		return x.Msg
	}
	return nil
}

type AppendLogsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastAppendedSeq uint64 `protobuf:"varint,1,opt,name=last_appended_seq,json=lastAppendedSeq,proto3" json:"last_appended_seq,omitempty"`
}

func (x *AppendLogsReply) Reset() {
	*x = AppendLogsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkv_v0_replication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendLogsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendLogsReply) ProtoMessage() {}

func (x *AppendLogsReply) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_v0_replication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendLogsReply.ProtoReflect.Descriptor instead.
func (*AppendLogsReply) Descriptor() ([]byte, []int) {
	return file_dkv_v0_replication_proto_rawDescGZIP(), []int{1}
}

func (x *AppendLogsReply) GetLastAppendedSeq() uint64 {
	if x != nil {
		return x.LastAppendedSeq
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToSequence uint64 `protobuf:"varint,1,opt,name=to_sequence,json=toSequence,proto3" json:"to_sequence,omitempty"`
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkv_v0_replication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_v0_replication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_dkv_v0_replication_proto_rawDescGZIP(), []int{2}
}

func (x *CommitRequest) GetToSequence() uint64 {
	if x != nil {
		return x.ToSequence
	}
	return 0
}

type CommitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastCommittedSeq uint64 `protobuf:"varint,1,opt,name=last_committed_seq,json=lastCommittedSeq,proto3" json:"last_committed_seq,omitempty"`
}

func (x *CommitReply) Reset() {
	*x = CommitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkv_v0_replication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReply) ProtoMessage() {}

func (x *CommitReply) ProtoReflect() protoreflect.Message {
	mi := &file_dkv_v0_replication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReply.ProtoReflect.Descriptor instead.
func (*CommitReply) Descriptor() ([]byte, []int) {
	return file_dkv_v0_replication_proto_rawDescGZIP(), []int{3}
}

func (x *CommitReply) GetLastCommittedSeq() uint64 {
	if x != nil {
		return x.LastCommittedSeq
	}
	return 0
}

var File_dkv_v0_replication_proto protoreflect.FileDescriptor

var file_dkv_v0_replication_proto_rawDesc = []byte{
	0x0a, 0x18, 0x64, 0x6b, 0x76, 0x2f, 0x76, 0x30, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6b, 0x76, 0x2e,
	0x76, 0x30, 0x1a, 0x14, 0x64, 0x6b, 0x76, 0x2f, 0x76, 0x30, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x65,
	0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x6b, 0x76, 0x2e, 0x76, 0x30, 0x2e, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3d,
	0x0a, 0x0f, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2a, 0x0a, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x65, 0x64, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x6c, 0x61,
	0x73, 0x74, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x53, 0x65, 0x71, 0x22, 0x30, 0x0a,
	0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22,
	0x3b, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c,
	0x0a, 0x12, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x6c, 0x61, 0x73, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x53, 0x65, 0x71, 0x32, 0x8a, 0x01, 0x0a,
	0x0b, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0a,
	0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x18, 0x2e, 0x64, 0x6b, 0x76,
	0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x64, 0x6b, 0x76, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x28,
	0x01, 0x12, 0x36, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x15, 0x2e, 0x64, 0x6b,
	0x76, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x64, 0x6b, 0x76, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6f, 0x75, 0x6e, 0x67, 0x6a, 0x6f, 0x6f,
	0x6e, 0x2d, 0x6c, 0x65, 0x65, 0x2f, 0x64, 0x6b, 0x76, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x6b, 0x76,
	0x2f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dkv_v0_replication_proto_rawDescOnce sync.Once
	file_dkv_v0_replication_proto_rawDescData = file_dkv_v0_replication_proto_rawDesc
)

func file_dkv_v0_replication_proto_rawDescGZIP() []byte {
	file_dkv_v0_replication_proto_rawDescOnce.Do(func() {
		file_dkv_v0_replication_proto_rawDescData = protoimpl.X.CompressGZIP(file_dkv_v0_replication_proto_rawDescData)
	})
	return file_dkv_v0_replication_proto_rawDescData
}

var file_dkv_v0_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dkv_v0_replication_proto_goTypes = []interface{}{
	(*AppendLogRequest)(nil), // 0: dkv.v0.AppendLogRequest
	(*AppendLogsReply)(nil),  // 1: dkv.v0.AppendLogsReply
	(*CommitRequest)(nil),    // 2: dkv.v0.CommitRequest
	(*CommitReply)(nil),      // 3: dkv.v0.CommitReply
	(*PutRequest)(nil),       // 4: dkv.v0.PutRequest
}
var file_dkv_v0_replication_proto_depIdxs = []int32{
	4, // 0: dkv.v0.AppendLogRequest.msg:type_name -> dkv.v0.PutRequest
	0, // 1: dkv.v0.Replication.AppendLogs:input_type -> dkv.v0.AppendLogRequest
	2, // 2: dkv.v0.Replication.Commit:input_type -> dkv.v0.CommitRequest
	1, // 3: dkv.v0.Replication.AppendLogs:output_type -> dkv.v0.AppendLogsReply
	3, // 4: dkv.v0.Replication.Commit:output_type -> dkv.v0.CommitReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dkv_v0_replication_proto_init() }
func file_dkv_v0_replication_proto_init() {
	if File_dkv_v0_replication_proto != nil {
		return
	}
	file_dkv_v0_kvstore_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dkv_v0_replication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkv_v0_replication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendLogsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkv_v0_replication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkv_v0_replication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dkv_v0_replication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dkv_v0_replication_proto_goTypes,
		DependencyIndexes: file_dkv_v0_replication_proto_depIdxs,
		MessageInfos:      file_dkv_v0_replication_proto_msgTypes,
	}.Build()
	File_dkv_v0_replication_proto = out.File
	file_dkv_v0_replication_proto_rawDesc = nil
	file_dkv_v0_replication_proto_goTypes = nil
	file_dkv_v0_replication_proto_depIdxs = nil
}
